const imageDataScroll = [
  {
    id: 1,
    img: "https://www.yummytummyaarthi.com/wp-content/uploads/2015/05/1-63.jpg",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 10,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 10,
  },
  {
    id: 2,
    img: "https://backend-nodejs-suby.onrender.com/uploads/1710923375138.avif",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 299,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 299,
  },
  {
    id: 3,
    img: "https://www.thedeliciouscrescent.com/wp-content/uploads/2016/05/Easy-Hyderabadi-Chicken-Biryani.jpg",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 399,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 399,
  },
  {
    id: 4,
    img: "https://static.vecteezy.com/system/resources/previews/047/329/504/large_2x/delicious-indian-food-biryani-with-shrimp-and-vegetables-being-served-in-a-round-metal-bowl-photo.jpg",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 499,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 499,
  },
  {
    id: 5,
    img: "https://th.bing.com/th/id/R.08c8c149545d564043af2c1aaefcb00d?rik=VLPToHNxIM%2fUFQ&riu=http%3a%2f%2fi.huffpost.com%2fgen%2f4446994%2fimages%2fo-CHICKEN-BIRYANI-facebook.jpg&ehk=JTU0MU7FktP3ohba1ga5whyd7j5PfdTJeo9IHueE7%2bk%3d&risl=&pid=ImgRaw&r=0",
    name: "Hyderbad Briyanni",
    Region: "Chines",
    Area: "warangal",
    offer: "50% off above 499",
    price: 599,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 599,
  },
  {
    id: 6,
    img: "https://plus.unsplash.com/premium_photo-1694141252026-3df1de888a21?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8YmlyeWFuaXxlbnwwfHwwfHx8MA%3D%3D",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 699,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 699,
  },

  {
    id: 7,
    img: "https://backend-nodejs-suby.onrender.com/uploads/1710923375138.avif",
    name: "Hyderbad Briyanni",
    Region: "Chines",
    Area: "warangal",
    offer: "50% off above 499",
    price: 799,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 799,
  },
  {
    id: 8,
    img: "https://imgmediagumlet.lbb.in/media/2024/04/6614fd1d0b7fe8704919d324_1712651549895.jpg",
    name: "Hyderbad Briyanni",
    Region: "Chines",
    Area: "warangal",
    offer: "50% off above 499",
    price: 899,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 899,
  },
  {
    id: 9,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw-n9-CM9YOf1PziU1T8CXqgpY6YWsllN1Mw&s",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 299,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 299,
  },
  {
    id: 10,
    img: "https://static.toiimg.com/thumb/imgsize-23456,msid-115336489,width-600,resizemode-4/115336489.jpg",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 399,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 399,
  },
  {
    id: 11,
    img: "https://backend-nodejs-suby.onrender.com/uploads/1710925098445.avif",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 499,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 499,
  },
  {
    id: 12,
    img: "https://assets.box8.co.in/rectangle-19x10/xxhdpi/product/5007",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 159,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 159,
  },
  {
    id: 13,
    img: "https://i.pinimg.com/736x/7a/05/45/7a05459be80a8587e9abe3bb3e6b7c33.jpg",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 699,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 699,
  },
  {
    id: 14,
    img: "https://backend-nodejs-suby.onrender.com/uploads/1710939863166.avif",
    name: "Hyderbad Briyanni",
    Region: "South India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 499,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 499,
  },
  {
    id: 15,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Sadhya_DSW.jpg/1024px-Sadhya_DSW.jpg",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 899,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 899,
  },
  {
    id: 15,
    img: "https://imgmediagumlet.lbb.in/media/2024/04/6614fd1d0b7fe8704919d324_1712651549895.jpg",
    name: "Hyderbad Briyanni",
    Region: "North India",
    Area: "warangal",
    offer: "50% off above 499",
    price: 899,
    Discription: "Green Houses",
    Quantity: 1,
    totalPrice: 899,
  },
];

export default imageDataScroll;
